version: '3.7'
networks:
  weoja:
    external: true
    driver: overlay

services:
  test-adapter:
    image: test-adapter
    depends_on:
      - redis
    networks:
      - 'weoja'
    ports:
      - '3024:3000'

  redis:
    image: docker.io/bitnami/redis:6.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - RedisVolume:/bitnami/redis/data
    networks:
      - 'weoja'

volumes:
  RedisVolume:
